apiVersion: apps/v1
kind: Deployment
metadata:
  name: app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app
  template:
    metadata:
      labels:
        app: app
    spec:
      containers:
        - name: app
          image: <your-image-name>:<your-image-tag>
          env:
            - name: DB_HOST
              value: mysqldb
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: mysqldb-secret
                  key: MYSQLDB_USER
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysqldb-secret
                  key: MYSQLDB_ROOT_PASSWORD
            - name: DB_NAME
              valueFrom:
                secretKeyRef:
                  name: mysqldb-secret
                  key: MYSQLDB_DATABASE
            - name: DB_PORT
              value: "3306"
          ports:
            - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: app
spec:
  selector:
    app: app
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
